# Generated by Django 2.2 on 2020-12-16 22:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='code_name',
            name='neirong',
            field=models.CharField(max_length=3000, null=True),
        ),
    ]
